name: linux

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  perl:
    runs-on: ubuntu-latest

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1
      PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "perl:latest"
          - "perl:5.32"
          - "perl:5.30"
          - "perl:5.28"
          - "perl:5.26"
          - "perl:5.24"
          - "perl:5.22"
          - "perl:5.20"
          - "perl:5.18"
          - "perl:5.16"
          - "perl:5.14"
          - "perl:5.12"
          - "perl:5.10"
          - "perl:5.8"
          - "perldocker/perl:5.6.2"
          - "perldocker/perl:5.6.1"
          - "perldocker/perl:5.6.0"

    container:
      image: ${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      #      - name: Install Dependencies
      #        run: curl -sL https://git.io/cpm | perl - install -g --show-build-log-on-failure
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: make regen
        run: make regen
      - name: revert timestamp update
        run: "git checkout parts/inc/version ||:"
      - name: diff
        run: git diff --quiet
      - name: make
        run: make
      - name: Run Tests
        run: make test
