name: testsuite

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  ubuntu:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1
      PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: perl -V
      - run: perl Makefile.PL
      - run: make regen
      - name: revert timestamp update
        run: "git checkout parts/inc/version ||:"
      - run: make
      - name: Run Tests
        run: make test

  linux:
    runs-on: ubuntu-latest
    needs: [ubuntu]

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1
      PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "perl:latest"
          - "perl:5.36"
          - "perl:5.34"
          - "perl:5.32"
          - "perl:5.30"
          - "perl:5.28"
          - "perl:5.26"
          - "perl:5.24"
          - "perl:5.22"
          - "perl:5.20"
          - "perl:5.18"
          - "perl:5.16"
          - "perl:5.14"
          - "perl:5.12"
          - "perl:5.10"
          - "perl:5.8"
          - "perldocker/perl:5.6.2"
          - "perldocker/perl:5.6.1"
          - "perldocker/perl:5.6.0"

    container:
      image: ${{ matrix.perl-version }}

    steps:
      # use v1 for git diff later
      - uses: actions/checkout@v3
      - run: perl -V
      - run: perl Makefile.PL
      - run: make regen
      - name: revert timestamp update
        run: "git checkout parts/inc/version ||:"
      - run: make
      - name: Run Tests
        run: make test

  macOS:
    runs-on: macOS-latest
    needs: [ubuntu]

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1
      PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    steps:
      - uses: actions/checkout@v3
      - name: Set up Perl
        run: brew install perl
      - run: perl -V
      - run: perl Makefile.PL
      - run: make regen
      - name: revert timestamp update
        run: "git checkout parts/inc/version ||:"
      - run: make
      - name: Run Tests
        run: make test

  windows:

    runs-on: windows-latest
    needs: [ubuntu]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" >> $GITHUB_PATH
      - run: perl -V
      - run: perl Makefile.PL
      - run: make
      - name: Run Tests
        run: make test
